In [1]:
import pandas as pd


C:\Users\sthaa\AppData\Local\Temp\ipykernel_26376\2035458946.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df = pd.read_csv("mtcars (3).csv")

In [3]:
df.head()

Unnamed: 0       vichle_names   mpg  cyl   disp     hp  drat     wt   qsec  \
0           0          Mazda RX4  21.0    6  160.0  110.0  3.90  2.620  16.46   
1           1      Mazda RX4 Wag  21.0    6  160.0  110.0  3.90  2.875  17.02   
2           2         Datsun 710   NaN    4  108.0   93.0  3.85  2.320  18.61   
3           3     Hornet 4 Drive  21.4    6  258.0    NaN  3.08  3.215  19.44   
4           4  Hornet Sportabout  18.7    8  360.0  175.0  3.15  3.440  17.02   

   v_Shape   am  gear  carb  
0      0.0  1.0   4.0     4  
1      0.0  1.0   4.0     4  
2      1.0  1.0   4.0     1  
3      1.0  0.0   3.0     1  
4      0.0  0.0   NaN     2

In [4]:
df.tail()

Unnamed: 0    vichle_names   mpg  cyl   disp     hp  drat     wt  qsec  \
27          27    Lotus Europa  30.4    4   95.1  113.0  3.77  1.513  16.9   
28          28  Ford Pantera L  15.8    8  351.0  264.0  4.22  3.170  14.5   
29          29    Ferrari Dino  19.7    6  145.0  175.0  3.62  2.770  15.5   
30          30   Maserati Bora  15.0    8  301.0  335.0  3.54  3.570  14.6   
31          31      Volvo 142E  21.4    4  121.0  109.0  4.11  2.780  18.6   

    v_Shape   am  gear  carb  
27      1.0  1.0   5.0     2  
28      0.0  1.0   5.0     4  
29      0.0  1.0   5.0     6  
30      0.0  1.0   5.0     8  
31      1.0  1.0   4.0     2

In [5]:
df.shape    

(32, 13)

In [6]:
df.shape[0]

32

In [7]:
df.describe()

Unnamed: 0        mpg        cyl        disp          hp       drat  \
count   32.000000  30.000000  32.000000   32.000000   31.000000  31.000000   
mean    15.500000  20.076667   6.187500  230.721875  147.870968   3.609032   
std      9.380832   6.196366   1.785922  123.938694   69.363171   0.538766   
min      0.000000  10.400000   4.000000   71.100000   52.000000   2.760000   
25%      7.750000  15.275000   4.000000  120.825000   96.000000   3.080000   
50%     15.500000  19.200000   6.000000  196.300000  123.000000   3.700000   
75%     23.250000  22.475000   8.000000  326.000000  180.000000   3.920000   
max     31.000000  33.900000   8.000000  472.000000  335.000000   4.930000   

              wt       qsec    v_Shape         am       gear     carb  
count  32.000000  29.000000  30.000000  28.000000  29.000000  32.0000  
mean    3.217250  17.601379   0.433333   0.428571   3.724138   2.8125  
std     0.978457   1.535459   0.504007   0.503953   0.751026   1.6152  
min     1.513000  14.500000   0.000000   0.000000   3.000000   1.0000  
25%     2.581250  16.870000   0.000000   0.000000   3.000000   2.0000  
50%     3.325000  17.420000   0.000000   0.000000   4.000000   2.0000  
75%     3.610000  18.610000   1.000000   1.000000   4.000000   4.0000  
max     5.424000  20.010000   1.000000   1.000000   5.000000   8.0000

In [8]:
df.isna().mean() * 100


Unnamed: 0       0.000
vichle_names     0.000
mpg              6.250
cyl              0.000
disp             0.000
hp               3.125
drat             3.125
wt               0.000
qsec             9.375
v_Shape          6.250
am              12.500
gear             9.375
carb             0.000
dtype: float64

In [9]:
missing_columns = list(df.columns[df.isnull().any()])



In [10]:
meandf = df.__deepcopy__()


In [11]:
df.dtypes

Unnamed: 0        int64
vichle_names     object
mpg             float64
cyl               int64
disp            float64
hp              float64
drat            float64
wt              float64
qsec            float64
v_Shape         float64
am              float64
gear            float64
carb              int64
dtype: object

In [12]:
numerical_columns = list(df._get_numeric_data().columns)

categorical_columns = set(df.columns) - set(numerical_columns)

print(numerical_columns)
print(categorical_columns)

['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'v_Shape', 'am', 'gear', 'carb']
{'vichle_names'}


In [13]:
nme = ["Arjn","Supip","Rajan"]
deg = ["MBA","BCA","M.Tech"]
scr = [40,50,60]

In [14]:
dict = {"name":nme,'degree':deg,"score":scr}
df1 = pd.DataFrame(dict)

In [15]:
df1

name  degree  score
0   Arjn     MBA     40
1  Supip     BCA     50
2  Rajan  M.Tech     60

In [16]:
df1

name  degree  score
0   Arjn     MBA     40
1  Supip     BCA     50
2  Rajan  M.Tech     60

In [17]:
df1.index.name = "my_index"
df1

name  degree  score
my_index                      
0          Arjn     MBA     40
1         Supip     BCA     50
2         Rajan  M.Tech     60

In [18]:
df1.to_csv("file1.csv")

In [19]:
df1.to_json("file1.json")

In [20]:
df_json = pd.read_json("file1.json")

In [21]:
df_json

name  degree  score
0   Arjn     MBA     40
1  Supip     BCA     50
2  Rajan  M.Tech     60

## Random regression dataframe

In [22]:
from sklearn.datasets import make_regression

In [36]:
features, target, coefficients = make_regression(n_samples = 100,
                                                 n_features= 3,
                                                 n_informative= 2,
                                                 n_targets= 1,
                                                 noise= 0.0,
                                                 coef = True,
                                                 random_state= 1)


In [37]:
print("feature Matrix\n", features[:3])
print("Target Vector\n", target[:3])
print("coefficients\n",coefficients[:3])

feature Matrix
 [[-1.1191154  -0.89055558  1.9560789 ]
 [ 0.84616065  0.31515939 -0.85951594]
 [ 0.58281521  0.04221375 -1.10061918]]
Target Vector
 [-104.43925569   63.13782001   35.76065963]
coefficients
 [58.15774073 44.19042807  0.        ]


Make-Classification Example


In [39]:
from sklearn.datasets import make_classification

features1, target1 = make_classification(n_samples= 100,
                                         n_features= 3,
                                         n_informative= 3,
                                         n_redundant= 0,
                                         n_classes = 2,
                                         weights = [.25,.75],
                                         random_state= 1)

In [40]:
print("feature Matrix\n", features1[:3])
print("Target Vector\n", target1[:3])

feature Matrix
 [[ 1.06354768 -1.42632219  1.02163151]
 [ 0.23156977  1.49535261  0.33251578]
 [ 0.15972951  0.83533515 -0.40869554]]
Target Vector
 [1 0 0]


In [41]:
type(features1)

numpy.ndarray

In [42]:
type(target1)

numpy.ndarray

In [44]:
import numpy as np

In [46]:
x_data = np.array(features1)
y_data = np.array(target1)

In [52]:
new_data = np.append(x_data,y_data.reshape(-1,1),axis=1)
new_data.shape

(100, 4)

In [49]:
df = pd.DataFrame(new_data)

In [53]:
df.head(10)

0         1         2    3
0  1.063548 -1.426322  1.021632  1.0
1  0.231570  1.495353  0.332516  0.0
2  0.159730  0.835335 -0.408696  0.0
3 -0.706121 -1.032810  1.394780  1.0
4  0.844490 -0.619972  1.087911  1.0
5  0.559395 -1.458154  1.476024  1.0
6 -2.342800 -0.862142 -0.702237  0.0
7 -0.502301 -1.112665  0.994591  1.0
8  0.918051 -1.318131  1.376723  1.0
9 -0.637175  0.590889 -0.220413  0.0

In [64]:
df1 = pd.DataFrame(data= features1,columns=["feature1","feature2","feature3"])
df2 = pd.DataFrame(data = target1,columns=["target"])
df3 = df1.join(df2)

In [65]:
df3.head(10)

feature1  feature2  feature3  target
0  1.063548 -1.426322  1.021632       1
1  0.231570  1.495353  0.332516       0
2  0.159730  0.835335 -0.408696       0
3 -0.706121 -1.032810  1.394780       1
4  0.844490 -0.619972  1.087911       1
5  0.559395 -1.458154  1.476024       1
6 -2.342800 -0.862142 -0.702237       0
7 -0.502301 -1.112665  0.994591       1
8  0.918051 -1.318131  1.376723       1
9 -0.637175  0.590889 -0.220413       0

### Make-blob example


In [73]:
from sklearn.datasets import make_blobs
features_blob, classes_blob = make_blobs(n_samples=100,
                                 centers = 3,
                                 n_features = 2,
                                 random_state=0)



In [74]:
print(features_blob[:3])
print(classes_blob[:3])

[[2.63185834 0.6893649 ]
 [0.08080352 4.69068983]
 [3.00251949 0.74265357]]
[1 0 1]


In [79]:
df_blob = pd.DataFrame(data=features_blob, columns=["features1","features2"])


In [80]:
df_blob.shape

(100, 2)

In [81]:
df_blob["cluster_id"] = classes_blob

In [82]:
df_blob.shape

(100, 3)

In [78]:
df_blob.head()

features1  features2  cluster_id
0   2.631858   0.689365           1
1   0.080804   4.690690           0
2   3.002519   0.742654           1
3  -0.637628   4.091047           0
4  -0.072283   2.883769           0

In [76]:
import plotly.express as px
fig = px.scatter(df_blob,x="features1",y="features2",color = "cluster_id")
fig.show()