In [1]:
import numpy as np

In [9]:
scaler = 1
scaler

1

In [4]:
vector = np.array([1, 2])
vector

array([1, 2])

In [10]:
matrix = np.array([[1, 2],[3, 4]])
matrix

array([[1, 2],
       [3, 4]])

In [12]:
tensor = np.array([[[1, 2], [3, 2]], [[1, 7], [5, 4]]])
tensor

array([[[1, 2],
        [3, 2]],

       [[1, 7],
        [5, 4]]])

In [15]:
#Matrix addition
matrix1 = np.array([[1, 7],[3, 8]])
matrix2 = np.array([[1, 2],[3, 4]])
finalmatrix = matrix1 + matrix2
finalmatrix

array([[ 2,  9],
       [ 6, 12]])

In [16]:
#Matrix Multiplication
matrixmulti = finalmatrix * 3
matrixmulti

array([[ 6, 27],
       [18, 36]])

In [32]:
#Vector Magnitude
vectorA = np.array([10, 20, 30])
vectorB = np.array([5, -20, 45])

In [33]:
dotproductAB = np.dot(vectorA, vectorB)
dotproductAB

1000

In [34]:
magnitudeB = np.linalg.norm(vectorB)
magnitudeB

49.49747468305833

In [35]:
magnitudeC = dotproductAB / magnitudeB
magnitudeC

20.203050891044214

In [36]:
projectionC = (dotproductAB / (magnitudeB**2))*vectorB
projectionC

array([ 2.04081633, -8.16326531, 18.36734694])

In [44]:
#Multiplication
matrixnewA = np.array([0, 2 , 4, 6])
matrixnewB = np.array([1, 3, 5, 7])

np.matmul(matrixnewA, matrixnewB)

68

In [45]:
#Trnaspose
transposeA = [[0, 1], [2, 3], [4, 5]]
np.transpose(transposeA)

array([[0, 2, 4],
       [1, 3, 5]])

In [50]:
identitymatrixone = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
othermatrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.matmul(identitymatrixone, othermatrix) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])