# Question 1 (10 marks)

You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's.

Increment the large integer by one and return the resulting array of digits.

Example 1:

Input: digits = [1,2,3]

Output: [1,2,4]

Explanation: The array represents the integer 123.

Incrementing by one gives 123 + 1 = 124.

Thus, the result should be [1,2,4].

Use function and input method



In [ ]:
#Answer

In [3]:
def plusOne(digits:list)->list:
    """This function adds one on the list as a whole

    Args:
        digits (list): list of numbers

    Returns:
        list: returns the added list as output
    """
    # length of the list
    n = len(digits)
    # getting the element from the last of the list
    for i in range(n-1, -1, -1):
        if digits[i] < 9:# if the number is less than 9 then add 1
            digits[i] += 1
            return digits
        digits[i] = 0 # if the number is 9 than add 1
    return [1] + digits # returns by adding 1 to the front if it gets executed

# input from the user
digits = list(map(int,input("Enter the numbers in list (giving spaces)").split()))
print(plusOne(digits))


[1, 2, 4]


# Question 2 (15 marks)
Given an m x n matrix mat, return an array of all the elements of the array in a diagonal order.

To understand the question better, print out the input matrix below and compare that to the output.

Example 1:

Input: mat = [[1,2,3],[4,5,6],[7,8,9]]

Output: [1,2,4,7,5,3,6,8,9]

Example 2:

Input: mat = [[1,2],[3,4]]

Output: [1,2,3,4]


In [ ]:
#Answer

In [18]:
import numpy as np
def diagonalorder(mat:list)->list:
    """This function takes the matrix and returns the elements of array in diagonal order

    Args:
        mat (list): List of matrix

    Returns:
        list: the required output in diagonal order
    """
    row = len(mat)
    col = len(mat[0])
    
    result = []
    np_matrix = np.array(mat)
    matrix = np_matrix.reshape(-1)
    print(matrix)
    
    n = len(matrix)
    for i in range(0,2):
        result.append(matrix[i])
    
    for i in range(2, n - 2):
        if i % 2 == 0:
            i -= 2
            result.append(matrix[i])
        elif i % 2 == 1:
            i += 3
            result.append(matrix[i])
    for i in range(n-2,n):
        result.append(matrix[i])
    print(result)
         
mat = [[1,2,3],[4,5,6],[7,8,9]]
print(diagonalorder(mat))


[1 2 3 4 5 6 7 8 9]
[1, 2, 1, 7, 3, 9, 5, 8, 9]
None


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question 3 (15 Marks)

Given a rows x cols binary matrix filled with 0's and 1's, write a function and use input method to find the largest rectangle containing only 1's and return its area. your output must also print out the part of the matrix with maximum area corresponding to part 1.

Input: matrix = [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]

Output: 

part a: 6

part b: [['1', '1', '1'],
         ['1', '1', '1']]




you can print the example matrix above to get better visual understanding of the quesion

Use function and input method!

In [5]:
def areaOfTraiangle(matrix:list):
    """returns the area of the matrix and also the part of the matrix

    Args:
        matrix (list): takes the matrix of 0's and 1'set
    """
    rows = len(matrix)
    cols = len(matrix[0])
    
    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] == "1":
                print(i,j)
                
matrix = [["1","0","1","0","0"],
          ["1","0","1","1","1"],
          ["1","1","1","1","1"],
          ["1","0","0","1","0"]]
print(areaOfTraiangle(matrix))

0 0
0 2
1 0
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 3
None


# Good Luck 